<?php

declare(strict_types=1);

namespace App\Presenters;

use Nette\Application\UI\Form;
use Nette\Utils\Html;
use Tracy\Debugger;

class ProductPresenter extends BasePresenter
{
    /**
     * @var \App\Forms\ProductForm @inject
     */
    public $productFormFactory;

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }

    public function actionDefault(int $page = 1)
    {
        $this->template->products = $this->database->table('products');

        $this->template->number = 1;

        Debugger::barDump($this->getSession('basket')->products);
    }

    public function actionDetail($productId)
    {
        $product = $this->database->table('products')->get(['id' => $productId]);

        $this['productAmountForm']->setDefaults($product);

        $this->template->product = $product;
        $this->template->productQuantity = $this->getSession('product')->quantity;
    }

    /**
     * Product form factory.
     */
    protected function createComponentProductAmountForm(): Form
    {
        return $this->productFormFactory->create();
    }
}
