<?php

declare(strict_types=1);

namespace App\Presenters;

use Nette;
use Nette\Application\UI\Form;


class SignPresenter extends BasePresenter
{
    /**
     * @var \App\Forms\SignInForm @inject
     */
    public $signInFormFactory;

    public function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
    }

	/**
	 * Sign-in form factory.
	 */
	protected function createComponentSignInForm(): Form
	{
        return $this->signInFormFactory->create();
	}


	public function actionOut(): void
	{
		$this->getUser()->logout();
		$this->flashMessage('You have been signed out.');
		$this->redirect('Homepage:');
	}
}
